name: Review

on:
  pull_request:

jobs:
  ruby-style-guide:
    name: RuboCop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
      - name: rubocop
        uses: reviewdog/action-rubocop@v2
        with:
          fail_on_error: true
          rubocop_extensions: rubocop-rails rubocop-performance rubocop-rspec rubocop-shopify
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review # Default is github-pr-check
          filter_mode: diff_context
          rubocop_flags: "-c .rubocop.yml"
  brakeman:
    name: Brakeman
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
      - name: brakeman
        uses: reviewdog/action-brakeman@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review # Default is github-pr-check
