name: Linters

on: [pull_request]

jobs:
  ruby-style-guide:
    name: RuboCop scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
      - name: RuboCop style check
        uses: reviewdog/action-rubocop@v2
        with:
          github_token: ${{ secrets.github_token }}
          rubocop_version: 1.20
          rubocop_flags: "-c .rubocop.yml"
          rubocop_extensions: rubocop-rails:2.11 rubocop-performance:1.11 rubocop-rspec:2.4 rubocop-shopify:2.2
          fail_on_error: true
          level: warning
  brakeman:
    name: Brakeman scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Brakeman vulnerability scan
        uses: reviewdog/action-brakeman@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review # Default is github-pr-check
          fail_on_error: true
          filter_mode: diff_context
