name: Style checks

on:
  push:
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: checkout branch

      - uses: andrewmcodes/rubocop-linter-action@v3.3.0
        name: Initializing RuboCop Linter
        with:
          action_config_path: ".github/config/rubocop_linter_action.yml" # Note: this is the default location
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
